language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: qDB0qwA3XVD+NykxRqS5UikLIRzYZHnJJYzrOya4TK74rdMBIXYLegdiKGlVKmI3z/GvYliormt6EXMWoOahShao29Q27mKgVj7mLWXHEpFgk+qdY90vPe751v921BNKKZkEjC6FIgYNUQV6snyYET9o3MHg91PLzMQrLwwX4NI=
  - secure: Q95zm1Ikj1XLbHuTrcLMKxk0COKlpGrHcYwen8TEETgBo8JONHBBppQ18srF+eKMtgS6WARPtwG/39/Wm/ddaZJs0nobQxHXEzoOkA3kh86x5IZUks79i68/jpUSMKXIzkznGnUZUsFiK7xpr8zckUgld94Q+zyZfPtYokSP1VI=
